### PR TITLE
Fix bad payload returning a 500 instead of a 400

### LINKED ISSUE #8: Return a 400 on bad payload instead of a 500

### PR DESCRIPTION
**Pull request by dalloriam**
Fixes #8

### CODE REVIEW

File: bin/menmosd/tests/menmosd_query.rs [hunk 1]
```diff
@@ -41,4 +43,28 @@ async fn query_pagination() -> Result<()> {
...
+    #[derive(Serialize)]
+    struct BadQuery {
+        ya: String,
+    }
+
+    let client = reqwest::Client::new();
+    let response = client
+        .post(&format!("{}/query", &cluster.directory_url))
+        .header("authorization", &cluster.directory_password)
+        .json(&BadQuery { ya: "yeet".into() })
```
Comment (laurentlp) [inline bin/menmosd/tests/menmosd_query.rs:59]: Arguably the most awesome line of code I've read in my life!!!

**Review by laurentlp — APPROVED** [review]
EZ fix! Goof job!
